### ISSUE TITLE
Scale percentage textsize

### ISSUE THREAD

**Issue by geertberkers** [MackHartley/RoundedProgressBar#1]
I would suggest to scale the percentage textsize.
I see it's get smaller in small progress bars, but does not increase in bigger ones.

![Screenshot_20200904-033123__01](https://user-images.githubusercontent.com/8653723/92189539-37946f80-ee5f-11ea-8ac2-8127f79dc169.png)

**Comment by MackHartley** [comment]
Actually the text does not change size depending on the width of the container. I just set a slightly smaller size for this example. I probably shouldn't have done that though as I can see how that's confusing to readers of the readme

**Comment by MackHartley** [comment]
Just reviewed the code again and can confirm that these text sizes were set manually by me, so this isn't a bug. The suggestion to have the text size pre-populate based on the progress bar height is interesting though. I've noted that for potential future enhancements. Thanks for the first issue!

**Comment by MackHartley** [comment]
Also if more people want this particular feature feel free to leave a comment here. However, I suspect most people will be fine with just setting what ever text size they want on the progress bar
