### ISSUE TITLE
ProgressListener

### ISSUE THREAD

**Issue by sherwin14** [MackHartley/RoundedProgressBar#17]
Does it have like ProgressListener that will send an event once progress change?

**Comment by MackHartley** [comment]
Hey @sherwin14, it does not currently have a progress change listener. I can add this in a future enhancement though as that's a good idea. Thanks for the suggestion!

**Comment by MackHartley** [comment]
Fyi I added it to the project for this repo: https://github.com/MackHartley/RoundedProgressBar/projects/1

I'll try to get around to it when I can, but time is a bit tight for me at the moment unfortunately. Perhaps sometime mid August I can look into it.
