### ISSUE TITLE
Transparent background required.

### ISSUE THREAD

**Issue by xxxifan** [MackHartley/RoundedProgressBar#18]
Hi, it's a nice library but here's a situation I need to use a semi transparent background within progressbar, but afte  I set `rpbBackgroundColor` it's a black background. Any change to support this function?

**Comment by MackHartley** [comment]
Hey! Thanks for using the library! Could you send some code, and maybe a picture, that shows your issue? I can certainly try to get a fix in for that sometime soon. More info would help me add that change.

**Comment by xxxifan** [comment]
just use like sample code with a transparent background color:

```
  <com.mackhartley.roundedprogressbar.RoundedProgressBar
    android:layout_width="match_parent"
    android:layout_height="40dp"
    app:rpbBackgroundColor="#00ffffff"
    app:rpbCornerRadius="20dp"
    app:rpbProgress="40"
    app:rpbProgressColor="@color/text_accent_ff5757"
    app:rpbShowProgressText="false" />
```
get result with a black background
![20210829202356](https://user-images.githubusercontent.com/1215833/131250235-bad55236-5f63-4c6f-8f70-9797d089612f.png)

I didn't mean  to use a full transparent background, just showing this case. our ui design is like this
![123](https://user-images.githubusercontent.com/1215833/131250323-a434d9b9-dea2-4d3d-86e4-601738db2def.png)

this should be a common use case. :p

**Comment by MackHartley** [comment]
Yea I agree, I'll need to get a fix in for this. I'll take a look into this on Tuesday and see if I can get it fixed for you folks. If you're in a rush feel free to try identifying the issue and opening up a PR for the bug fix!

**Comment by MackHartley** [comment]
Just wanted to follow up on this, I can't take a look at this today as work is quite busy. I can certainly take a look this weekend though. Sorry about the delay!

**Comment by MackHartley** [comment]
@xxxifan I think I fixed the issue, the progress bar now takes a transparent value for the background or the progress (aka foreground) drawable.

![updatedColors](https://user-images.githubusercontent.com/10659285/132112562-220827a1-88a4-4aea-9982-a7d4987aa05f.png)

Also, if you're using this library feel free to add a reference to your app here, with an image of your usage:
https://github.com/MackHartley/RoundedProgressBar/blob/master/who_uses_rpb.md

This allows others to see how you're using the library and also might direct more traffic to your app!

**Comment by MackHartley** [comment]
FYI: I just updated the readme with the new version. To get support for transparency please use version `2.1.1`.

**Comment by xxxifan** [comment]
Thanks in advance!

> Also, if you're using this library feel free to add a reference to your app here, with an image of your usage:
> https://github.com/MackHartley/RoundedProgressBar/blob/master/who_uses_rpb.md
> 
> This allows others to see how you're using the library and also might direct more traffic to your app!

I'd love to do this right after we published our APP :D

**Comment by MackHartley** [comment]
Great! When you want to add your app, feel free to follow this PR example: https://github.com/MackHartley/RoundedProgressBar/pull/11

If you have any other issues or questions just let me know
