### ISSUE TITLE
let us set custom text there not only % so we can set there progress status like 9/10 

### ISSUE THREAD

**Issue by gulabsagevadiya** [MackHartley/RoundedProgressBar#20]
This will helpful to show custom progress to app users

**Comment by MackHartley** [comment]
Hi @gulabsagevadiya! Thanks for the suggestion. That's a good idea and I'd be happy to add such a feature. However, it might take a bit of time as the library is currently designed to only work with percentages. I'll look into this though!

**Comment by MackHartley** [comment]
Huh, what a coincidence. This got marked stale right as I finally got around to making these changes.

Sorry about the delay @gulabsagevadiya , I hope you and other devs are able to get use out of the new changes!
