### ISSUE TITLE
Good development

### ISSUE THREAD

**Issue by HaveMoney** [MackHartley/RoundedProgressBar#21]
Great library, I think it should be richer, for example, circular progress bar, etc.

**Comment by MackHartley** [comment]
Hi @HaveMoney, thanks for your kind words! While I do think it would be cool if the library featured circular progress bars, there are already good open source libraries for that so I don't think there's a need to make this library cover that use case.

Here are a few examples of libraries that have what you're looking for:
https://github.com/lopspower/CircularProgressBar
https://github.com/korre/android-circular-progress-bar
