### ISSUE TITLE
Why can't Max be set for progress?

### ISSUE THREAD

**Issue by afrazakhavan** [MackHartley/RoundedProgressBar#24]
how to set progressview.setmax();

How can I access the following method?

**Comment by MackHartley** [comment]
Hi @afrazakhavan, sorry about the delay in response. The progress bar only goes from 0 -> 100, there is no way to change that. If you have a different range, like 1 -> 50, you could just do the math to get it to fit the 0 -> 100 range.

You can also have the progress text say whatever you want by setting the `ProgressTextFormatter` : https://github.com/MackHartley/RoundedProgressBar/blob/master/roundedprogressbar/src/main/java/com/mackhartley/roundedprogressbar/RoundedProgressBar.kt#L506

**Comment by MackHartley** [comment]
If that doesn't make sense or solve your issue just lemme know
